# Site settings
title: MeLavoro
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
payment_url: "http://localhost:3000" #TODO: link al servizio Rails per inserimento dati registrazione e fatturazione
url: "https://melavoro.com" # the base hostname & protocol for your site
logo: /assets/img/logo_melavoro.png
author: Copyright &copy; 2020 - KRYAX SRL
lang: it_IT
product_name: melavoro #identifica il prodotto da vendere nel nostro sistema


# Build settings
safe: true 
markdown: kramdown
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
collections:
  pricing:
    output: true
  service_descriptions:
    output: true

defaults:
  - scope:
      path: ""
      type: "pricing"
    values:
      layout: "service_price"
  - scope:
      path: ""
      type: "service_descriptions"
    values:
        layout: "service_description"


